'''
This script compares NACA airfoil coordinates taken from AirfoilTools website
against the one generated by the current module.

2025-03
'''

# IMPORTS
import numpy as np
import airfoil_mod as am
import matplotlib.pyplot as plt

# INPUTS

# Coordinate files of each airfoil
files = {'0012': 'airfoil_data/naca0012.dat',
         '2412': 'airfoil_data/naca2412.dat',
         '03012': 'airfoil_data/naca03012.dat',
         '13012': 'airfoil_data/naca13012.dat',
         '23012': 'airfoil_data/naca23012.dat'}

# EXECUTION

# Initialize dictionary to hold reference coordinates of each airfoil
ref_coord = {}

# Initialize dictionary to hold coordinates computed by airfoil_mod
am_coord = {}

# Chordwise locations for sampling
xx_sample = am.cos_bunching(0.0, 1.0, 61)

for airfoil_name, airfoil_file in files.items():

    xx, yy = am.read_coordinates(airfoil_file)
    ref_coord[airfoil_name] = {'xx':xx,'yy':yy}

    airfoil = am.nacafoil(airfoil_name, xx_sample, plot=False)
    xf = airfoil['x_coord']
    yf = airfoil['y_coord']

    am_coord[airfoil_name] = {'xx':xf,'yy':yf}

    fig = plt.figure()
    plt.plot(xx,yy,'o',label='reference')
    plt.plot(xf,yf,label='airfoil_mod')
    plt.xlabel('x')
    plt.ylabel('y')
    plt.title('NACA '+airfoil_name)
    plt.legend(loc='best')
    plt.axis('equal')
    plt.tight_layout()
    plt.show()